language: CSharp
sudo: true
install:
  - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo pt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - apt-get update
  - apt-get install -y dotnet=1.0.0.001331-1
script:
  - cd src/Starter.Web
  - dotnet restore
  - dotnet compile
  - tar -cvzf starter-web-${TRAVIS_BUILD_NUMBER}.tar.gz Starter.Web/bin
  - ls -al
before_deploy:
  - cp starter-web-${TRAVIS_BUILD_NUMBER}.tar.gz starter-web.tar.gz # Add ${TRAVIS_TAG} if you like
  - ls -al
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: starter-web.tar.gz # Add ${TRAVIS_TAG} if you like
  skip_cleanup: true
  on:
    tags: true
