install:
  - cinst gitversion.portable -pre -y
  - cinst 7zip.commandline -y
  - git config --global core.autocrlf true
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: ~\.dnx\bin\dnvm install latest
before_build:
  - dnu restore --no-cache
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: ls
build_script:
  - dnu publish src\Starter.Web\ -o buildout --configuration Release --no-source
after_build:
  - 7z.exe a starter-web.zip buildout\
  - ps: ls
test: off 
deploy:
  description: 'Starter $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token: $(GITHUB_OAUTH_TOKEN)
  artifact: starter-web.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
