install:
  - choco install gitversion.portable -pre -y
  - git config --global core.autocrlf true
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: ~\.dnx\bin\dnvm install latest
before_build:
  - dnu restore --no-cache
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - echo %GITVERSION_MAJOR%
  - echo %GITVERSION_SEMVER%
  - ps: ls
build_script:
  - dnu publish src\Starter.Web\ -o buildout --configuration Release --no-source
  - ps: ls
test: off 
deploy: off 
#  project: src/Starter.Web/project.json
