# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.1.0"

Vagrant.configure(2) do |config|

  config.vm.hostname = "starter"
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../src", "/src"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provider "parallels" do |p, override|
    # Guest Tools are unavailable.
    p.check_guest_tools = false
    p.functional_psf    = false
    p.name = "starter"
  end

$script = <<SCRIPT

echo "Update libz"
sudo apt-get -qq update 
sudo apt-get -qqy install unzip curl libunwind8 gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
sudo rm -rf /var/lib/apt/lists/*
echo "Install dnvm"
curl -sSL -v https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
echo "Install coreclr"
dnvm upgrade -r coreclr 

SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
# libcurl3-gnutls  
#   config.vm.provision "shell" do |s|
#     s.path = "Vagrantprovision-runtime.sh"
#   end
#   config.vm.provision "shell" do |s|
#     s.privileged = false
#     s.path = "Vagrantprovision-usertools.sh"
#   end
end
