# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.hostname = "starter"

  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
    s.privileged = false
  end

  config.vm.synced_folder "../", "/code"

  config.ssh.username = "vagrant"

end
